name: Compile and run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Compile and run
      run: for dir in day*; do cd $dir; mkdir -p build; cd build; cmake ..; make -j 4; cd ..; ./build/day*; cd ..; done
      
